### ISSUE TITLE
Prepare manuscript for Integration in Computo

### ISSUE THREAD

**Issue by jchiquet** [oliviergimenez/computo-deeplearning-occupany-lynx#1]
Dear Olivier, 

Now that your manuscript has been accepted for publication in Computo, we would need a few actions from you to help us in the production process. In particular,

- please make the github build action work again
- please include only the files needed for compilation (or indicate the subdirectories to be included) in order to limit the footprint when copying the repository on our side

Once this repository is cleaned up, we will make a copy in the Computo github group and put it in the final publication format. You will then be able to edit the proofs using pull-request.

Thanks again for choosing us to publish your work!

**Comment by oliviergimenez** [comment]
Done. Thank you for the big help !
